In [2]:
import pandas as pd
import numpy as np
from scipy.interpolate import interp1d
import glob
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
from scipy import *

In [3]:
df=pd.read_csv(r"C:\Users\kamat\Downloads\MWData\MWData\MW.csv")
df.columns=['1','2','3','4','5','6','7']
df['7'] =df['7'].apply(lambda str1:[float(x) for x in str1.split(",") if x.strip() != "" and x.strip()!="-"])

In [4]:
df

,1,2,3,4,5,6,7
0,0,0,MW,FP1,0,1017,"[38.0, 48.0, 51.0, 44.0, 48.0, 56.0, 56.0, 41...."
1,1,1,MW,FP1,1,889,"[83.0, 74.0, 65.0, 65.0, 66.0, 55.0, 43.0, 25...."
2,2,2,MW,FP1,4,1017,"[19.0, 10.0, -2.0, -9.0, -5.0, 3.0, 8.0, 7.0, ..."
3,3,3,MW,FP1,1,1017,"[17.0, 29.0, 36.0, 26.0, 21.0, 17.0, 17.0, 13...."
4,4,4,MW,FP1,8,952,"[77.0, 74.0, 69.0, 70.0, 76.0, 75.0, 76.0, 75...."
...,...,...,...,...,...,...,...
67630,67630,67630,MW,FP1,-1,1024,"[138.0, 135.0, 123.0, 96.0, 59.0, 38.0, 11.0, ..."
67631,67631,67631,MW,FP1,-1,1024,"[4.0, 5.0, -7.0, -12.0, -11.0, -17.0, 2.0, 52...."
67632,67632,67632,MW,FP1,-1,1024,"[96.0, 163.0, 208.0, 179.0, 129.0, 114.0, 140...."
67633,67633,67633,MW,FP1,-1,1024,"[-30.0, 4.0, 53.0, 85.0, 84.0, 72.0, 80.0, 85...."
67634,67634,67634,MW,FP1,-1,1024,"[41.0, 27.0, 41.0, 76.0, 88.0, 80.0, 83.0, 76...."

In [5]:
from pywt import wavedec
from sklearn.preprocessing import StandardScaler
from scipy.signal import butter, lfilter
from scipy.stats import skew, kurtosis
def resample(array):
     input_indices = np.linspace(0, len(array)-1, len(array))
     resampled_indices =np.linspace(0,len(array)-1,1024)
     interpolator =interp1d(input_indices,array,'linear')
     resampled_array =interpolator(resampled_indices)
     nyquist = 0.5 * 256
     normal_cutoff = (0.4999/nyquist) / nyquist
     b, a = butter(4, normal_cutoff, btype='low', analog=False)
     filtered_signal =np.array(lfilter(b, a, resampled_array))
     scaler = StandardScaler()
     resampled_array=scaler.fit_transform(filtered_signal.reshape(-1, 1)).reshape(-1)
     coeff=np.hstack(wavedec(resampled_array, 'dmey', level=4))
     scaler = StandardScaler()
     coeff=scaler.fit_transform(coeff.reshape(-1, 1)).reshape(-1)
     return np.array(coeff)

In [6]:
#resampled data
df['8'] = df.apply(lambda row: resample(row['7']), axis=1).to_numpy()

In [7]:
df

,1,2,3,4,5,6,7,8
0,0,0,MW,FP1,0,1017,"[38.0, 48.0, 51.0, 44.0, 48.0, 56.0, 56.0, 41....","[-1.808056217851663, -1.8080565189434912, -1.8..."
1,1,1,MW,FP1,1,889,"[83.0, 74.0, 65.0, 65.0, 66.0, 55.0, 43.0, 25....","[-1.7842384893947965, -1.7842402310833458, -1...."
2,2,2,MW,FP1,4,1017,"[19.0, 10.0, -2.0, -9.0, -5.0, 3.0, 8.0, 7.0, ...","[-1.5006364742366203, -1.5006369383070328, -1...."
3,3,3,MW,FP1,1,1017,"[17.0, 29.0, 36.0, 26.0, 21.0, 17.0, 17.0, 13....","[-1.5996251509622257, -1.5996263256467698, -1...."
4,4,4,MW,FP1,8,952,"[77.0, 74.0, 69.0, 70.0, 76.0, 75.0, 76.0, 75....","[-1.6068394241280342, -1.6068415051934268, -1...."
...,...,...,...,...,...,...,...,...
67630,67630,67630,MW,FP1,-1,1024,"[138.0, 135.0, 123.0, 96.0, 59.0, 38.0, 11.0, ...","[-1.6820353075195602, -1.682038006693816, -1.6..."
67631,67631,67631,MW,FP1,-1,1024,"[4.0, 5.0, -7.0, -12.0, -11.0, -17.0, 2.0, 52....","[-1.5513873187390268, -1.5513872669972717, -1...."
67632,67632,67632,MW,FP1,-1,1024,"[96.0, 163.0, 208.0, 179.0, 129.0, 114.0, 140....","[-1.7112290472673453, -1.7112336265257087, -1...."
67633,67633,67633,MW,FP1,-1,1024,"[-30.0, 4.0, 53.0, 85.0, 84.0, 72.0, 80.0, 85....","[-1.421716034757126, -1.4217053323372673, -1.4..."
67634,67634,67634,MW,FP1,-1,1024,"[41.0, 27.0, 41.0, 76.0, 88.0, 80.0, 83.0, 76....","[-1.716129338388266, -1.7161301349188554, -1.7..."

In [8]:
len(df['8'][2])

1266

In [9]:
x=[]
y=[]
for i in range(67635):
    x.append(
        np.array(df['8'][i]).flatten()
    )
    y.append(df['5'][i])
x = np.array(x)
y = np.array(y)

In [10]:
x.shape

(67635, 1266)

In [11]:
y.shape

(67635,)

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [13]:
from sklearn.model_selection import GridSearchCV
knn = KNeighborsClassifier(n_neighbors=20)
knn.fit(x_train,y_train)
y_predicted=knn.predict(x_test)
accuracy=accuracy_score(y_test,y_predicted)
accuracy

0.18200635765506026